# Generated by Django 5.0.6 on 2024-06-19 23:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 6, 19)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 6, 19)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.institution'),
            preserve_default=False,
        ),
    ]
